### ISSUE TITLE
ca.abs not found?

### ISSUE THREAD

**Issue by alexjc** [andersbll/neural_artistic_style#1]
Just installed everything from the repositories, and getting this error:

```
Traceback (most recent call last):
  File "neural_artistic_style.py", line 115, in <module>
    run()
  File "neural_artistic_style.py", line 107, in run
    cost = np.mean(net._update())
  File "/media/Data/bots/neural_artistic_style/style_network.py", line 144, in _update
    norm = ca.sum(ca.abs(style_grad))
AttributeError: 'module' object has no attribute 'abs'
```

Is the ca from GitHub not the right version to use? Thanks!

**Comment by andersbll** [comment]
I think you have an old version of CUDArray installed. `abs()` is defined [here](https://github.com/andersbll/cudarray/blob/master/cudarray/elementwise.py#L215).

**Comment by andersbll** [comment]
Ah, my bad! I think the CUDA-backend is failing to start and that you are running on NumPy which does not have `numpy.abs()`. I should remove `cudarray.abs()` from CUDArray and use `fabs()` instead.

**Comment by alexjc** [comment]
Thanks, how can I check why CUDA is failing? I have Torch running on CUDA fine.

**Comment by alexjc** [comment]
Also happy to see it installs and runs very well on Python 3.4 :-) One minor typo:

```
diff --git a/cudarray/numpy_backend/nnet/__init__.py b/cudarray/numpy_backend/nnet/__init__.py
index a5bd172..3aac4a1 100644
--- a/cudarray/numpy_backend/nnet/__init__.py
+++ b/cudarray/numpy_backend/nnet/__init__.py
@@ -4,4 +4,4 @@ from .conv_bc01 import *
 from .pool_bc01 import *
 from .lrnorm_bc01 import *
 from .conv import *
-from pool import *
+from .pool import *
```

**Comment by andersbll** [comment]
Try this for starters: 
http://andersbll.github.io/deeppy-website/installation-guide.html#verify-cuda-back-end

**Comment by alexjc** [comment]
OK, it was failing to import `libcudart.so.7` (or using wrong version), so running the script with `LD_LIBRARY_PATH=/usr/local/cuda-7.0/lib64/` prefix fixed it.  Would linking statically be easier for installing `cudarray`, since it needs to be compiled on each user machines anyway?

EDIT: Moving new error to a new issue.
