### ISSUE TITLE
UnboundLoacalError

### ISSUE THREAD

**Issue by PierreHao** [andersbll/neural_artistic_style#12]
I didn't install cuDNN, so i use max pooling instead of ave pooling. But when i run it, there is an error like this:
File "/usr/local/lib/python2.7/dist-packages/cudarray-0.1.dev0-py2.7-linux-x86_64.egg/cudarray/nnet/conv.py", line 92, in bprop
    filters._data, convout_d._data, b, c, f, img_shape,
UnboundLocalError: local variable 'b' referenced before assignment
Does anyone know what's the problem?

**Comment by andersbll** [comment]
I'll look into it!

**Comment by PierreHao** [comment]
Thank you! You have done a very great work, write this cool code according to the paper.

**Comment by andersbll** [comment]
Suprisingly, CUDArray's convolutions (im2col + matrix multiplications) are just af fast as those in cuDNN for the problem sizes of neural artistic style networks. If you are content with max pooling, you don't need to install cuDNN as it won't bring a noticeable speedup! :)

**Comment by PierreHao** [comment]
Yes, i don't need to install cuDNN with max pooling, with using max pooling, the problem UnboundLocalError: local variable 'b' referenced before assignment is strange, this is the code of cudarray

**Comment by andersbll** [comment]
The problem is fixed. Just update your installation of CUDArray.

**Comment by PierreHao** [comment]
Really? I use cudarray: https://github.com/andersbll/cudarray, i will try to update it
