### ISSUE TITLE
More style weight?

### ISSUE THREAD

**Issue by Hannessa** [andersbll/neural_artistic_style#14]
Is it possible to give more weight to style, so that the subject's shape is altered more aggressively and the resulting output is more abstract?

I tried setting --subject-ratio to a very low float with many decimals, but it doesn't seem to have much effect beyond the default value.

**Comment by andersbll** [comment]
You are probably initializing with the subject image. Use --init-noise to control the noise on the initial image. E.g. --subject-ratio 0 --init-noise 1 should only give you a style/texture reconstruction.

**Comment by Hannessa** [comment]
Great! Thanks, now I understand better how it works.
