### ISSUE TITLE
Error when size of images are equal

### ISSUE THREAD

**Issue by DmitryUlyanov** [andersbll/neural_artistic_style#15]
Hello, this probably issues `deeppy` and not the script. If I pass images of equal size i have an error. So for example: 

```
python neural_artistic_style.py --subject images/margrethe_picasso.jpg --style images/margrethe.jpg
```

And error:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  src/nnet/cudnn.cpp:196: The GPU program failed to execute.
Aborted (core dumped)
```

Can you check what's happening ? 

Thank you! 
Dmitry

**Comment by andersbll** [comment]
Strange! I suspect it might be a problem with your CUDA installation. Make sure your version of cuDNN matches your CUDA SDK. You could also try a smaller image. It might be an out of memory error.

**Comment by DmitryUlyanov** [comment]
It happens if you do not do backprop. So reinitialized layers in the end of `__init__` and it worked out.

**Comment by andersbll** [comment]
Ok, that sounds more like an error in CUDArray/DeepPy. I'll look into it. :)

**Comment by andersbll** [comment]
Got it, thanks a lot for reporting this error!
