### ISSUE TITLE
Running neural_artistic_style.py without CUDA uses only 1 core

### ISSUE THREAD

**Issue by ghost** [andersbll/neural_artistic_style#17]
Hi, 
I'm running this script without CUDA and trying to make it work on CPU alone. Problem is, only 1 core is being used out of 4. Is it a bug or multiple CPU cores are not supported?

**Comment by andersbll** [comment]
Your observation is absolutely right. The convolution operations are not very efficient on the CPU - they are not even parallelized. If I have the time at some point I would like to implement them more efficiently. Probably using im2col and matrix multiplications.

**Comment by ghost** [comment]
Ok, thanks. Closing this issue then.

**Comment by andersbll** [comment]
Fine, I'll update this if anything should happen. :)
