### ISSUE TITLE
ValueError: invalid pooling method for "masked" pooling

### ISSUE THREAD

**Issue by alexjc** [andersbll/neural_artistic_style#2]
Fixed the backend, now a different error:

```
Traceback (most recent call last):
  File "neural_artistic_style.py", line 119, in <module>
    run()
  File "neural_artistic_style.py", line 82, in run
    layers, img_mean = vgg19_net(args.vgg19, pool_method='avg')
  File "/media/Data/bots/neural_artistic_style/matconvnet.py", line 46, in vgg19_net
    layers.append(pool_layer(pool_method, border_mode))
  File "/media/Data/bots/neural_artistic_style/matconvnet.py", line 21, in pool_layer
    border_mode=border_mode,
  File "/media/Data/bots/neural_artistic_style/deeppy/deeppy/feedforward/convnet_layers.py", line 72, in __init__
    self.pool_op = ca.nnet.PoolB01(win_shape, pad, strides, method)
  File "/media/Data/bots/neural_artistic_style/cudarray/cudarray/nnet/pool.py", line 21, in __init__
    raise ValueError('invalid pooling method for "masked" pooling')
ValueError: invalid pooling method for "masked" pooling
```

Any ideas?

**Comment by andersbll** [comment]
Sorry about the not-so-informative error messages! You need to install [cuDNN](https://developer.nvidia.com/cudnn). Just place the library files and header files along with your CUDA installation at `/usr/local/cuda-7.0`.

CUDArray doesn't require cuDNN - but some operations like average pooling are only implemented in cuDNN.

**Comment by alexjc** [comment]
Thanks, I installed the header and libraries into that folder, how do I tell CUDArray to pick it up—or give me a better error message?

**Comment by andersbll** [comment]
`make clean` CUDArray and reinstall. Remember to `export CUDNN_ENABLED=1` first. :)

**Comment by alexjc** [comment]
It compiled all the `cudnn.cpp` files and installed fine, but not being picked up at runtime.  The exception is the same.

Can I force it with `CUDARRAY_BACKEND=cudnn` or find out if it's working with `cudarray._backend`? (Couldn't figure that part out. Thanks for all your help, I love the idea of a Python version of this and willing to help.)

**Comment by andersbll** [comment]
Did you also do `python setup.py ...`? Be sure the cuDNN Cython wrapper is installed.

**Comment by alexjc** [comment]
I had, but it silently said everything was OK and `setup.py clean` didn't remove the `.cpp` files.  Also, when doing `sudo python3 setup.py install` it forgets the `CUDNN_ENABLED=1` so that was another mistake.

Now that part is working, next exception :-)

**Comment by alexjc** [comment]
In general, it'd be nice to have an easy way to check if `cudnn` is indeed supported, like being able to force it to use `cuda` with an environment variable—the same for `cudnn`?

**Comment by billzorn** [comment]
What was the exact procedure for fixing this?

I originally forgot to `export CUDNN_ENABLED=1`, but after sorting that out and rebuilding/reinstalling cudarray I'm still having the same problem. I've had the v3.0 candidate of cudnn and cuda 7.0 installed the whole time. Also I'm using the default python2.7 on Ubuntu.

**Comment by andersbll** [comment]
i have added a command to clean up after Cython. Just run `python setup.py clean` for CUDArray.

If you do `sudo python setup.py install`, you should be aware the `CUDNN_ENABLED` environment variable won't be visible to root. I think you need to transfer environment variables by executing `sudo -E python setup.py install`

**Comment by billzorn** [comment]
Awesome, seems to be working now. Thanks.

**Comment by jugg1024** [comment]
hello   @andersbll   @billzorn billzorn ,  i meet the exact same problem , i'm sure i'v set the CUDNN_ENABLED=1 and install cudarray , deeppy,for that i  enter  the cudarray_backend( print(cudarray._backend) = cuda ). and I  download the cudnn and put it into /usr/local/cuda-7.0 . But still i meet the problem. is there something to do with the cuda version ?
my cuda version is 7.0.28 cudnn is 7.0.58.
 Another question is,  im not sure about the "cuDNN Cython wrapper" how can i check it?
just now i test one img and it takes almost 4hours for 50 iters. so im sure i don't make use of the gpu?
thank very much if you can help.
sorry for bother. now its working after using the  sudo -E python setup.py install

**Comment by andersbll** [comment]
And you have cleaned your Cython-regenerated files with `python setup.py clean`. Try printing the `CUDNN_ENABLED` environment variable in setup.py to see if it is set properly during installation.

To check for cuDNN acceleration: Try `print(cudarray.nnet.conv._default_impl)`. If it says `cudnn` you're good. If it says `matmul`, CUDArray is using its own convolution and pooling operations.

**Comment by jugg1024** [comment]
new problem @andersbll  my pc gpu has only 1g memory . So it ran out of memory when do conv using GPU() . can i set somewhere to reduce to gpu memory use?

Another one : when i try to do the same install on our server . this problem show again "invalid pooling method for "masked" pooling"  .Then I try to debug ,first make clean ,python clean ,and make all the files writable by  sudo chmod -R 777 filenames ,and  I add print(os.environ['CUDNN_ENABLED'])  to setup.py ,then sudo make ,sudo make install , sudo -E python setup.py install, print(os.environ['CUDNN_ENABLED']) gave 1 .then install deeppy .after that ,i do print(cudarray._backend) . it gave "cuda". print(cudarray.nnet.conv._default_impl) ,it gave "matmul"  . the only difference is that . CUDA version on server is cuda-7.5. i have try make clean and python setup.py clean for hundred of times,  any help?
second question solved .  I delete all the generated files . And first install cudnn , carefully link the libs, then set all the environment variable, then make . thank you ! now  it's so fast!

**Comment by andersbll** [comment]
Good to hear! The only way to get around the memory problem is to use smaller images.

**Comment by andersbll** [comment]
I have added average pooling to CUDArray. This means that cuDNN is no longer a requirement. I believe the speed of the method is about the same with or without cuDNN.
