### ISSUE TITLE
Style scaling

### ISSUE THREAD

**Issue by jnordberg** [andersbll/neural_artistic_style#24]
Would it be possible to normalise the style images and add something like a --style-scale option?

For example given the following images:

pyramid.jpg
![pyramid](https://cloud.githubusercontent.com/assets/95886/11318764/1978c166-9060-11e5-8517-5a3f44df1481.jpg)

perlin256.jpg
![perlin256](https://cloud.githubusercontent.com/assets/95886/11318770/3a969b20-9060-11e5-8472-c67f1487dc09.jpg)

perlin512.jpg
![perlin512](https://cloud.githubusercontent.com/assets/95886/11318772/3db7d756-9060-11e5-971c-cb6418980184.jpg)

The results become:

![pyramid_perlin512_i500](https://cloud.githubusercontent.com/assets/95886/11318784/a2a0cde4-9060-11e5-9067-2879b479c09f.png)

![pyramid_perlin256_i500](https://cloud.githubusercontent.com/assets/95886/11318785/a4735524-9060-11e5-8b0d-5fb799d3bef4.png)

**Comment by andersbll** [comment]
Hi there! I'm not sure what you are thinking of by 'normalize the style image'. Regarding the --style-scale, this is just a convenience feature that resizes the style image to some size before propagating it up the convnet, right?

**Comment by jnordberg** [comment]
Hey! What I'm looking for is a way to have the same style image produce roughly the same results for different sized subjects (I realise now that my example is backwards :D)

Maybe just by resizing the style to match the subjects size while keeping the aspect ratio. And then the --style-scale factor would be applied to the style image. Like that you can know that --style foo.jpg with --style-scale 2.1 produces the same effect on all input images.
