### ISSUE TITLE
vagg19_net KeyError normalization at matconvnet.py 

### ISSUE THREAD

**Issue by LeeHyungDo** [andersbll/neural_artistic_style#27]
i am trying to run this code. and i completed setting the requirement( Deeppy, cuDnn, choose imagenet-vgg-verydeep-19), vgg-verydeep-19 file is located at this project directory.

but i get error like below. 

Traceback (most recent call last):
  File "neural_artistic_style.py", line 139, in <module>
    run()
  File "neural_artistic_style.py", line 99, in run
    layers, img_mean = vgg19_net(args.vgg19, pool_method=args.pool_method)
  File "/home/ubuntu/LeeHD/neural_artistic_style-master/neural_artistic_style-master/matconvnet.py", line 35, in vgg19_net
    img_mean = matconvnet['normalization'][0][0][0].astype(dp.float_)
KeyError: 'normalization'

what should i do to fix this error?

**Comment by rnikhill** [comment]
MatConvNet recently switched over from beta16 to beta17 and changed their pre-trained models accordingly. Neural-Artistic-Style apparently only works with the beta16 format, which you can download from [here](http://www.vlfeat.org/matconvnet/models/beta16/)

**Comment by andersbll** [comment]
Hey, thank you both for the info. I have now switched to the new file format. Hopefully it won't change anytime soon. :)

**Comment by kapyar** [comment]
Hey, I got the same issue and when I download new `imagenet-vgg-verydeep-19.mat` from beta16 then I got following problem

`CUDArray: CUDA back-end not available, using NumPy.
Traceback (most recent call last):
  File "neural_artistic_style.py", line 139, in <module>
    run()
  File "neural_artistic_style.py", line 117, in run
    args.smoothness)
  File "/Users/yaroslav/Documents/NaUKMA/NeuronArtist/neural_artistic_style/style_network.py", line 88, in __init__
    self.x._setup(x_shape)
AttributeError: 'Parameter' object has no attribute '_setup'`

Does someone know how to solve this problem?
Thanks

**Comment by andersbll** [comment]
Hi, I think you need to pull the latest version of DeepPy/Neural artistic style.

**Comment by kapyar** [comment]
Did you mean this one https://github.com/andersbll/deeppy ?

**Comment by andersbll** [comment]
Yes.

**Comment by kapyar** [comment]
Thanks, I've sold this problem, I think the reason was that I wasn't use `sudo` command when run `python setup.py install`
