### ISSUE TITLE
Intermediary image saving

### ISSUE THREAD

**Issue by Leo-Mrl** [andersbll/neural_artistic_style#28]
Hello,

I was wondering if it was possible de save some intermediary images, like the ones described in the paper by Leon Gatys that represent style and content reconstruction respectively (see Figure 1 in the paper for details).
Is there a way to do that ?

**Comment by andersbll** [comment]
I think you can simply adjust [subject](https://github.com/andersbll/neural_artistic_style/blob/master/neural_artistic_style.py#L82) and [style](https://github.com/andersbll/neural_artistic_style/blob/master/neural_artistic_style.py#L85) weights. You specify them in tuples of (layer #, weight).

**Comment by Leo-Mrl** [comment]
Hey,
I actually just tried that with a white noise image as the subject input, with a very low subject/style weight ratio, and it yields the results I am looking for. Thanks a lot !
