### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'float' and 'ndarray'

### ISSUE THREAD

**Issue by alexjc** [andersbll/neural_artistic_style#3]
Thanks for all your help with this, I figure it's either making the software more reliable or helping others with documenting the installation issues :-)

Here's my next callstack:

```
Traceback (most recent call last):
  File "neural_artistic_style.py", line 121, in <module>
    run()
  File "neural_artistic_style.py", line 113, in run
    cost = np.mean(net._update())
  File "/media/Data/bots/neural_artistic_style/style_network.py", line 145, in _update
    weight = float(self.style_weights[l]) / norm
TypeError: unsupported operand type(s) for /: 'float' and 'ndarray'
```

**Comment by andersbll** [comment]
Indeed! :)

This is a strange error. I have tried running my code on both Python 2.7 and 3.3 and it works. Can you print the type and contents of the two operands?

**Comment by alexjc** [comment]
I'm on Python 3.4 but it shouldn't make that much difference.

```
weights: <class 'numpy.float64'> 0.2
norm: <class 'cudarray.cudarray.ndarray'> [  3.06112453e+14]
```

**Comment by andersbll** [comment]
I don't know if there has been a change between 3.3 and 3.4, but `float(self.style_weights[l])` should return a `float` not `numpy.ndarray`. I'll try to look it up.

**Comment by alexjc** [comment]
It's `norm` that's an array.  That comes out of `ca.sum`.

**Comment by andersbll** [comment]
Hey, the problem only occurs using Python 3.4 (I haven't figured out the exact problem).

You can quick fix it by replacing the line with the following. You also need to do this in line 136.

```
weight = float(self.style_weights[l] / np.array(norm))
```

**Comment by alexjc** [comment]
OK, it's working. Working faster than expected even on a pretty good resolution image!

Thanks for your help!

**Comment by andersbll** [comment]
Yes, I was also pleasantly surprised by the speed!

Thank you for all the feedback - I really should try to make CUDArray easier to install.

**Comment by alexjc** [comment]
Having some clear error messages on initialization, or warnings (e.g. "Falling back to numpy backend") would help a lot even identifying the error.  Also, `setup.py clean` that works and a way to specify CUDNN as a parameter to that script rather than environment variable.

Looking forward to seeing how it turns out!
