### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by lqhuy93** [andersbll/neural_artistic_style#31]
File "neural_artistic_style.py", line 99, in run
    layers, pixel_mean = vgg_net(args.network, pool_method=args.pool_method)
  File "F:\Neural image\matconvnet.py", line 37, in vgg_net
    weights = np.transpose(weights, (3, 2, 0, 1)).astype(dp.float_)
MemoryError

I've received this error. How to fix it?

**Comment by lqhuy93** [comment]
OK problem solved. I just post here for who have the same issue:
- 1: I test this on Win8, haha
- 2: Try to reduce the number of layers on line 32 matconvnet.py, it's have 43 layers total, i tried in 35 layers and it worked
- 3: Reduce resolution of your images.

**Comment by andersbll** [comment]
Hey, that's good. You are very likely to experience out of memory errors if you run the method on large images on a GPU with only a few GBs of memory.

**Comment by busylee999** [comment]
Hi, do you know how much memory need in common case to process for example 500x500 picture?

**Comment by andersbll** [comment]
Sorry, I don't have the time to try this out. The memory footprint is not trivial to calculate as it highly depends on implementation technicalities.

**Comment by lqhuy93** [comment]
@busylee999 About 1GB if you run with GPU.

**Comment by busylee999** [comment]
@lqhuy93 thx a lot! Do you know something about time estimation for process one image size 500x500 for example?

**Comment by lqhuy93** [comment]
you can analyze the code and combine your computer specifications to estimate the running-time. It's quite fast with GPU (About 20-30 minutes for a good product)
