### ISSUE TITLE
number of iteration for a image?

### ISSUE THREAD

**Issue by streamgao** [andersbll/neural_artistic_style#35]
How many iterations it takes for one image to run?
20? 30?

**Comment by FabienLavocat** [comment]
You can run as many iteration as you want. The default is 500.
The number of iteration will depend on your taste and what you want to achieve with your image.

**Comment by streamgao** [comment]
If so, it already takes me 20hours for 20 iterations to be run.

Which parameter I can set for less iterations?

XI GAO
gaoxi1992@hotmail.commailto:gaoxi1992@hotmail.com

On Apr 17, 2016, at 20:34, Fabien Lavocat <notifications@github.com<mailto:notifications@github.com>> wrote:

You can run as many iteration as you want. The default is 500.
The number of iteration will depend on your taste and what you want to achieve with your image.

**Comment by FabienLavocat** [comment]
You can add `--iterations XX` where XX is your number of iteration.
Running the script on a CPU will take you forever. You need a GPU if you don't want to spend your life waiting :)
