### ISSUE TITLE
AttributeError: 'StyleNetwork' object has no attribute '_params'

### ISSUE THREAD

**Issue by oscarriddle** [andersbll/neural_artistic_style#47]
Hi Andersbll,

Thanks for your upload. I tried it as your instructions and now encountered an ArributeError when running neural_artistic_style.
Here is the log:

root@giga:/home/xiaoluncao/neural_artistic_style-master# python neural_artistic_style.py --subject images/tuebingen.jpg --style images/starry_night.jpg
CUDArray: CUDA back-end not available, using NumPy.
style_img (448, 576, 3)
subject_img (600, 800, 3)
OUTER_IT:  0 SCALE: 2.0
Traceback (most recent call last):
  File "neural_artistic_style.py", line 182, in <module>
    run()
  File "neural_artistic_style.py", line 164, in run
    params = net._params
AttributeError: 'StyleNetwork' object has no attribute '_params'

Not quite sure about this error. I installed cudarray without CUDA SDK. 

Thanks,
oscarriddle

**Comment by andersbll** [comment]
Hi there, it seems that your neural artistic style code is  using an old DeepPy interface. `net._params` should be `net.params`.

**Comment by oscarriddle** [comment]
Hi, 
After sending this issue, I just located the problem and corrected it. 
I didn't run through CUDA acceleration, and it still works well for me.
Though the iteration went quite slow then when I tried to set argument that "--subject-ratio 1". 
This is really helpful and inspired me a lot. Thanks for your sharing!!
